language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

branches:
  only:
    - source

before_install:
  - npm install -g hexo

install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
  - git config user.name jimcheung
  - git config user.email hi.jinhu.zhang@gmail.com
  - sed -i "s/gh_token/${ACCESS_TOKEN}/g" ./_config.yml
  - hexo clean
  - hexo generate -d

script:
  - hexo deploy